[global]
user_agent=YAP (Yet Another PBX) / Asterisk

;====================TRANSPORT====================

[IPv4-UDP]
type=transport
protocol=udp
bind=0.0.0.0

[IPv4-TCP]
type=transport
protocol=tcp
bind=0.0.0.0

;[IPv4-TLS]
;type=transport
;protocol=tls
;bind=127.0.0.1
;cert_file=/asterisk_certs/voip.crt
;priv_key_file=/asterisk_certs/voip.key
;method=tlsv1_2

[IPv6-UDP]
type=transport
protocol=udp
bind=[::1]

[IPv6-TCP]
type=transport
protocol=tcp
bind=[::1]

;[IPv6-TLS]
;type=transport
;protocol=tls
;bind=[::1]
;cert_file=/asterisk_certs/voip.crt
;priv_key_file=/asterisk_certs/voip.key
;method=tlsv1_2
